/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import javax.swing.JFrame;
import java.sql.*;

/**
 *
 * @author lavri
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("LogIn");
    }
     ///Inchiderea JFrame-ului 
    public void CloseFrame(){
        super.dispose();
    }
    public static String getUsername(){
        return UserText.getText();
    }
    ///Adaugare in baza de date campionat->utlizator

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UserText = new javax.swing.JTextField();
        PassText = new javax.swing.JPasswordField();
        LogInBut = new javax.swing.JButton();
        ToSignInBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 120, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/account(1).png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 450));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 310, -1));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 156, 310, -1));

        UserText.setBackground(new java.awt.Color(0, 204, 204));
        UserText.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        UserText.setForeground(new java.awt.Color(255, 255, 255));
        UserText.setBorder(null);
        jPanel1.add(UserText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 48, 310, 30));

        PassText.setBackground(new java.awt.Color(0, 204, 204));
        PassText.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        PassText.setForeground(new java.awt.Color(255, 255, 255));
        PassText.setBorder(null);
        jPanel1.add(PassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 310, 30));

        LogInBut.setBackground(new java.awt.Color(255, 102, 102));
        LogInBut.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        LogInBut.setForeground(new java.awt.Color(255, 255, 255));
        LogInBut.setText("Login");
        LogInBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogInBut.setFocusTraversalPolicyProvider(true);
        LogInBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInButActionPerformed(evt);
            }
        });
        jPanel1.add(LogInBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        ToSignInBut.setBackground(new java.awt.Color(255, 102, 102));
        ToSignInBut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        ToSignInBut.setForeground(new java.awt.Color(255, 255, 255));
        ToSignInBut.setText("Dont have Account");
        ToSignInBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ToSignInBut.setFocusTraversalPolicyProvider(true);
        ToSignInBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToSignInButActionPerformed(evt);
            }
        });
        jPanel1.add(ToSignInBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogInButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButActionPerformed
        // TODO add your handling code here:
        try(Connection conn=DatabaseConnection.getConnection()){
            String user=UserText.getText().trim();
            char[] Pass=PassText.getPassword();
            String pass=new String(Pass).trim();
            if(user.isEmpty() || pass.isEmpty() ){
                javax.swing.JOptionPane.showMessageDialog(this,"Toate campurile sunt obligatorii!",
                "Eroare",javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            ///VERIFICARE USERNAME SI PAROLA
            String checkQuery1="SELECT username,password FROM utilizator WHERE username=? AND password=?";
            try(PreparedStatement checkStmt=conn.prepareStatement(checkQuery1)){
                checkStmt.setString(1,user);
                checkStmt.setString(2,pass);
                ResultSet rs=checkStmt.executeQuery();
                if(!rs.next()){
                    javax.swing.JOptionPane.showMessageDialog(this,
                    "Username sau parola gresita",
                    "Eroare",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                    UserText.setText("");
                    PassText.setText("");
                    return;
                }
            }catch (SQLException e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Eroare la verificarea username-ului si a parolei: " + e.getMessage(),
                    "Eroare",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            } 
        Dashboard dashboard=new Dashboard();
        dashboard.setVisible(true);
        ///ma mai gandesc daca inchi login frame ul
        CloseFrame();
        }catch(Exception e){
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, 
            "Eroare la verificarea datelor: " + e.getMessage(),
            "Eroare", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
//        Dashboard dashboard=new Dashboard();
//        dashboard.setVisible(true);
    }//GEN-LAST:event_LogInButActionPerformed

    private void ToSignInButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToSignInButActionPerformed
           // TODO add your handling code here:
        SignIn signin=new SignIn();
        signin.setVisible(true);
        
    }//GEN-LAST:event_ToSignInButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInBut;
    private javax.swing.JPasswordField PassText;
    private javax.swing.JButton ToSignInBut;
    private static javax.swing.JTextField UserText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
