/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import javax.swing.JFrame;
import java.sql.*;
//import Forms.DatabaseConnection;
//import java.sql.Connection;
//import java.sql.PreparedStatement;
/**
 *
 * @author lavri
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public  SignIn() {
        initComponents();
        setTitle("SignIn");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);///inchid doar aceasta fereastra
        
    }
    ///Inchiderea JFrame-ului 
    public void CloseFrame(){
    super.dispose();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UserText = new javax.swing.JTextField();
        PassText = new javax.swing.JPasswordField();
        SignInBut = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EmailText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/signIn.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 130, 120));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign Up");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 480));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 340, -1));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 154, 340, -1));

        UserText.setBackground(new java.awt.Color(0, 204, 204));
        UserText.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        UserText.setForeground(new java.awt.Color(255, 255, 255));
        UserText.setBorder(null);
        UserText.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(UserText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 48, 340, 30));

        PassText.setBackground(new java.awt.Color(0, 204, 204));
        PassText.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        PassText.setForeground(new java.awt.Color(255, 255, 255));
        PassText.setBorder(null);
        PassText.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(PassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 340, 20));

        SignInBut.setBackground(new java.awt.Color(255, 102, 102));
        SignInBut.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        SignInBut.setForeground(new java.awt.Color(255, 255, 255));
        SignInBut.setText("Sign In");
        SignInBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignInBut.setFocusTraversalPolicyProvider(true);
        SignInBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButActionPerformed(evt);
            }
        });
        jPanel1.add(SignInBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 242, 340, -1));

        EmailText.setBackground(new java.awt.Color(0, 204, 204));
        EmailText.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        EmailText.setForeground(new java.awt.Color(255, 255, 255));
        EmailText.setBorder(null);
        EmailText.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(EmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 340, 30));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignInButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButActionPerformed
        // TODO add your handling code here:
        ///SE ADAUGA DATE IN BAZA DE DATE UTILIZATOR DACA SUNT CONFORME
        try(Connection conn=DatabaseConnection.getConnection()){
            String user=UserText.getText().trim();
            char[] Pass=PassText.getPassword();
            String pass=new String(Pass).trim();
            String email=EmailText.getText().trim();
             if(user.isEmpty() || pass.isEmpty() || email.isEmpty()){
                javax.swing.JOptionPane.showMessageDialog(this,"Toate campurile sunt obligatorii!",
                "Eroare",javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            ///VERIFICARE USERNAME
            String checkQuery1="SELECT COUNT(*) FROM  utilizator WHERE username=?";//? este placeholder, practic asteapta valoare pe care o va primi
            try(PreparedStatement checkStmt=conn.prepareStatement(checkQuery1)){
                checkStmt.setString(1,user);/// ? ia valoarea lui user si se pune 1 acolo pentru ca se vrea inceperea cu linia 1 
                ResultSet rs=checkStmt.executeQuery();
                if(rs.next() && rs.getInt(1)>0 ){///rs.next()->se muta pe prima linie a lui rs; rs.getInt(1)->ia valoarea de pe prima coloana
                    javax.swing.JOptionPane.showMessageDialog(this,
                    "Acest username este deja folosit",
                    "Eroare",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }catch (SQLException e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Eroare la verificarea username-ului: " + e.getMessage(),
                    "Eroare",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            ///VERIFICARE PAROLA
            String checkQuery2="SELECT COUNT(*) FROM utilizator WHERE password=?";
            try(PreparedStatement checkStmt=conn.prepareStatement(checkQuery2)){
                checkStmt.setString(1,pass);
                ResultSet rs=checkStmt.executeQuery();
                if(rs.next() && rs.getInt(1)>0){
                    javax.swing.JOptionPane.showMessageDialog(this,
                    "Aceasta parola este deja folosit",
                    "Eroare",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                    
                }
            }catch (SQLException e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Eroare la verificarea parolei: " + e.getMessage(),
                    "Eroare",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            ///VERIFICARE EMAIL
            String checkQuery3="SELECT COUNT(*) FROM utilizator WHERE email=?";
            try(PreparedStatement checkStmt=conn.prepareStatement(checkQuery3)){
                checkStmt.setString(1,email);
                ResultSet rs=checkStmt.executeQuery();
                if(rs.next() && rs.getInt(1)>0){
                     javax.swing.JOptionPane.showMessageDialog(this,
                    "Acest email este deja folosit",
                    "Eroare",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;       
                }
            }catch (SQLException e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Eroare la verificarea emailului: " + e.getMessage(),
                    "Eroare",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
           
            String query="INSERT INTO utilizator(username,password,email) VALUES(?,?,?)";
            try(PreparedStatement stmt=conn.prepareStatement(query)){
                stmt.setString(1,user);
                stmt.setString(2,pass);
                stmt.setString(3,email);
                int rowInserted=stmt.executeUpdate();
                if(rowInserted>0){
                    javax.swing.JOptionPane.showMessageDialog(this,"Inregistrare realizata cu succes",
                "Succes",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }   
            }
            
            CloseFrame();
                                                 
        }catch(Exception e){
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, 
            "Eroare la incarcarea datelor: " + e.getMessage(),
            "Eroare", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        
        
        
    }//GEN-LAST:event_SignInButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailText;
    private javax.swing.JPasswordField PassText;
    private javax.swing.JButton SignInBut;
    private javax.swing.JTextField UserText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
